server:
  port: 8080
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.korolkovrs.spring20.changelogs
