spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  main:
    allow-circular-references: true

