server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mongodb:
    embedded:
      version: 3.4.0
  data:
    mongodb:
      database: library

  batch:
    job:
      enabled: true

    jdbc:
      initialize-schema: always


mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.korolkovrs.spring26.changelogs

